### ISSUE TITLE
Backgrounded tabs do not send membership messages until foregrounded

### ISSUE THREAD

**Issue by dirkmc** [ipfs-shipyard/peer-star-app#104]
When a tab is in the background for several seconds Chrome puts it to sleep. When the tab is foregrounded, it immediately sends out a whole bunch of stored membership messages. We should find a way to make these messages go out as scheduled in the background

Example:
https://usercontent.irccloud-cdn.com/file/ZgIuPkwt/message-flood.gif

**Comment by dirkmc** [comment]
Some information about background tabs here:
https://developers.google.com/web/updates/2017/03/background_tabs

**Comment by pgte** [comment]
@dirkmc thanks for bringing this up!
Having read these explanations for background behaviour, I think that this line can be a problem:

https://github.com/ipfs-shipyard/peer-star-app/blob/7150dbcd34434600e22a33bee3af741c6d260bee/src/collaboration/membership-gossip-frequency-henristic.js#L26.

I think that replacing this with a `setTimeout` should make this issue go away.

**Comment by dirkmc** [comment]
@pgte ok I will try it now

**Comment by pgte** [comment]
@dirkmc I believe that the right way should be a recursive `setTimeout`, where the new timeout is only set after the previous one has been completed, (in order to avoid rapid consecutive timeout accumulation triggering).

**Comment by dirkmc** [comment]
Ok, that makes sense... we also need to make sure though that the timeout does actually get triggered regularly, otherwise this node will effectively stop participating in gossip. I will test and make sure that is the case.

**Comment by dirkmc** [comment]
So it looks like this is a false alarm. When I log out the heuristic samples, they occur regularly as expected.

I think the issue I was seeing in the simulator is actually that the browser is putting rendering to sleep. So the browser stores up a bunch of animation frames and when it wakes up it executes them all at once.

I did notice another issue however: if I create several replicas in the simulator, the samples get fired every 10 seconds instead of every second. I guess that Chrome notices that the processor is busy doing a bunch of stuff, so when the tab is backgrounded Chrome extends the interval by 10 times. I'm going to experiment with this and see if I can find a way to keep a consistent interval even when the browser tab is under load.

**Comment by dirkmc** [comment]
For my simulator I replaced the real networking stack with a simulated network. However with real networking in place the connection manager opens a web socket connection, which causes Chrome to turn off throttling even in background tabs:
```
There are a number of automatic exemptions from this throttling:
- Applications playing audio are considered foreground and aren’t throttled.
- Applications with real-time connections (WebSockets and WebRTC),
  to avoid closing these connections by timeout.
  The run-timers-once-a-second rule is still applied in these cases.
```

So as long as we always keep a web socket connection open then I think we won't have issues with Chrome throttling background tabs.
@pgte if we move to a new discovery mechanism will it be using WebSockets or WebRTC? If so I think we can close this issue

**Comment by pgte** [comment]
@jimpick Even in the case of WS or WebRTC, there is still throttling happening. I believe @jimpick  has seen issues that may be a manifestation of this happening (batched delayed membership messages).

**Comment by pgte** [comment]
So I believe that it should always be a good practise to replace `setInterval` with recursive `setTimeout`.

**Comment by pgte** [comment]
> The run-timers-once-a-second rule is still applied in these cases

(from https://developers.google.com/web/updates/2017/03/background_tabs)

**Comment by dirkmc** [comment]
@pgte I just want to make sure I understand the idea of replacing `setInterval` with `setTimeout`. Is it because that will prevent throttling, or is it because that will produce more consistent results somehow? Could you explain how?

**Comment by pgte** [comment]
It's because of the results.
Since the action of setInterval is asynchronous (the `sample`function is async), the process can still fire the setIntervals, but since each one gets throttled, they all pile up, and once the tab is visible, they all get unstuck at around the same time.

Another preventive measure would be to make the `sample` function synchronous (it is possible).

**Comment by dirkmc** [comment]
Yes I think that actually `sample()` doesn't need to be async, because [membership.needsUrgentBroadcast()](https://github.com/ipfs-shipyard/peer-star-app/blob/master/src/collaboration/membership.js#L120) no longer returns a promise

**Comment by pgte** [comment]
@dirkmc should now be fixed by #110. Could you confirm?

**Comment by dirkmc** [comment]
@pgte the code looks good to me.

If I don't have a websocket connection open, Chrome still puts the background tab to sleep, which means setInterval() fires less frequently. But I'm not sure if that's an issue as we will always have a web socket connection open, right?

**Comment by pgte** [comment]
@dirkmc I'm not so worried with throttling, but more with throttling having these weird pathological effect of flooding the network with membership messages.
Is there anything you can do to test that this effect is not happening after this one fix?

**Comment by pgte** [comment]
(@dirkmc just to be clear: even if the setInterval fires a bunch of them repeatedly after the tab awakens, the current code, being synchronous, should now prevent a lot of membership messages from being sent almost simultaneously.)

**Comment by dirkmc** [comment]
@pgte I have not seen the message flooding situation occurring - what I saw in the simulator was a rendering issue (animation frames getting delayed and then flooding on wake up). Sorry for the confusion, it was a false alarm on my side.

**Comment by pgte** [comment]
@dirkmc no, the confusion was mine. I guess what I was saying is that we need to prevent any flooding that this bug has the potential of causing.

**Comment by dirkmc** [comment]
I agree, I think it's good that there is no longer an `await` in there

So far I haven't seen any flooding in the simulator. It's a hard situation to test in a repeatable way because it requires waiting for the browser to put the tab to sleep. I will see if I can come up with a way to test as part of the simulator I'm building

**Comment by pgte** [comment]
Great! I'm closing this one then, please reopen if you spot this in the wild. Thank you!
(I'd like to know more about that simulator you're building, looks useful!)

**Comment by dirkmc** [comment]
Cool sounds good :)

I'm planning to release the simulator once I have leadership election working correctly and have had a chance to clean up the code, I'm pretty close, hopefully by the end of the week :)
