### ISSUE TITLE
The start promise should be rejected when IPFS fails to start

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/peer-star-app#125]
I was in a flaky network and noticed that IPFS failed to connect to ws star:

![23d06090-7bcf-4673-821f-56d67d6a2add](https://user-images.githubusercontent.com/1017236/48565938-91761f00-e8f1-11e8-9ab9-c03c37f91cef.png)

When this happens, the promise retuned from `app.start` is never rejected and stays pending indefinitely.

**Comment by satazor** [comment]
Actually, I'm not sure if it should be rejected because it defeats the purpose of offline-first.

**Comment by pgte** [comment]
Should be fixed in v0.10.0. Please reopen if that's not the case.
