### ISSUE TITLE
Failing tests in master

### ISSUE THREAD

**Issue by victorb** [ipfs-shipyard/peer-star-app#154]
I don't have the details myself, but if we want to be able to deploy peer-star-app, the tests on master should be passing. Currently they are not.

Last I heard, @jimpick was looking into solving the test issues.

**Comment by victorb** [comment]
Possible solution while we wait for a test cleanup (to be able to deploy) is to change `npm test` to run `echo "Currently fixing the tests... Please hold" && exit 0` and it should deploy cleanly.

@pgte @jimpick thoughts?

**Comment by pgte** [comment]
I think 201e17badb51ffba4ea62f1bbc5d29082d772fb8 may have fixed this.

**Comment by pgte** [comment]
I haven't seen this in the wild after applying 201e17badb51ffba4ea62f1bbc5d29082d772fb8. Please reopen this if you find this is not the case.
