### ISSUE TITLE
Add E2E pinner tests that we can run after deploy

### ISSUE THREAD

**Issue by victorb** [ipfs-shipyard/peer-star-app#155]
Currently, after a deploy, we're unsure if a pinner deployment actually was successful, without having to test peerpad or similar manually with opening/closing tabs, writing content and so on.

I propose to add a npm script we can call `test-deploy` which we can point to a running pinner and makes sure content is actually persisted.

The test would basically create a new collaboration with the specified pinner, add some content, then go offline once content has been pinned.

After 1-2 seconds, a fresh collaboration with the same conditions will be created, and we can assert that the collaborations end up with the same data.

**Comment by pgte** [comment]
Fixed via 3381c8ed8bf71c7ea6703bdea5ea021ae4173729
