### ISSUE TITLE
Health + Prometheus endpoints

### ISSUE THREAD

**Issue by victorb** [ipfs-shipyard/peer-star-app#156]
Currently, the application doesn't listen to any HTTP ports, making health checks difficult.

We should add two endpoints:

- `/health` that can simply return 200 as status code and "ok" as body for now
- `/prometheus` that implements https://github.com/siimon/prom-client similar as ws-star, see https://github.com/libp2p/js-libp2p-websocket-star-rendezvous/blob/master/src/routes.js

**Comment by eefahy** [comment]
notes on how to implement this for heroku checks: https://help.heroku.com/P1AVPANS/why-is-my-node-js-app-crashing-with-an-r10-error

**Comment by victorb** [comment]
Would be good if the `/health` endpoint returns some information about the pinner itself, especially the `PeerID` of the pinner, and the associated configuration values.
