### ISSUE TITLE
random test failure - stream ended with:0 but wanted:1

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/peer-star-app#160]
Running `npm test` on master succeeds, but I sometimes see failures as well:

```
  1) collaboration
       closes peer:
     Uncaught Error: stream ended with:0 but wanted:1
      at drain (node_modules/pull-reader/index.js:43:26)
      at /home/test1/peer-pad-load-test/peer-star-app/node_modules/pull-reader/index.js:63:18
      at /home/test1/peer-pad-load-test/peer-star-app/node_modules/pull-reader/index.js:20:7
      at onNext (node_modules/pull-catch/index.js:15:28)
      at drain (node_modules/stream-to-pull-stream/index.js:141:18)
      at Channel.<anonymous> (node_modules/stream-to-pull-stream/index.js:166:5)
      at Channel.emit (node_modules/libp2p-mplex/src/internals/channel.js:96:13)
      at emitErrorNT (node_modules/libp2p-mplex/node_modules/readable-stream/lib/internal/streams/destroy.js:80:8)
      at emitErrorAndCloseNT (node_modules/libp2p-mplex/node_modules/readable-stream/lib/internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)



Command failed: mocha --timeout 5000 --ui bdd --colors --exit test/node.js test/**/*.spec.js
null
null
Error: Command failed: mocha --timeout 5000 --ui bdd --colors --exit test/node.js test/**/*.spec.js
null
null
    at makeError (/home/test1/peer-pad-load-test/peer-star-app/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/test1/peer-pad-load-test/peer-star-app/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peer-star-app@0.10.2 test:node: `aegir test -t node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peer-star-app@0.10.2 test:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This is on my Linux machine:

Linux nuc 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by victorb** [comment]
Just to verify, which rendezvous server are the tests connected to? I see this sometimes when I connect to the publicly available rendezvous but never when I run one locally, so I'm thinking it's from connecting to a specific peer (maybe with old version or different OS).

**Comment by victorb** [comment]
Also, this issue has happened before: https://github.com/libp2p/js-libp2p/pull/221

Are we sure all deps are up-to-date?

**Comment by jimpick** [comment]
My deps were freshly checked out. I encountered it again, this time on my laptop:

```
  1) collaboration
       closes peer:
     Error: Uncaught Error: stream ended with:0 but wanted:1 (webpack://peerstarapp/node_modules/node-libs-browser/node_modules/events/events.js:59 <- node_modules/aegir/src/config/karma-entry.js:283403)





Some tests are failing
Error: Some tests are failing
    at Server (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/aegir/src/test/browser.js:12:16)
    at removeAllListeners (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/karma/lib/server.js:342:9)
    at webServer.close (/Users/jim/backblend/clients/protocol-labs/peer-pad/upstream/peer-star-app/node_modules/karma/lib/server.js:353:13)
    at Server.close (net.js:1565:9)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:187:15)
    at emitCloseNT (net.js:1618:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peer-star-app@0.10.2 test:webworker: `aegir test -t webworker`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peer-star-app@0.10.2 test:webworker script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jim/.npm/_logs/2018-11-30T03_10_27_202Z-debug.log
error Command failed with exit code 1.
```

Darwin jpmbp2.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

So it doesn't look it it's specific to either my Linux environment or my OS X environment.

**Comment by jimpick** [comment]
> Just to verify, which rendezvous server are the tests connected to? I see this sometimes when I connect to the publicly available rendezvous but never when I run one locally, so I'm thinking it's from connecting to a specific peer (maybe with old version or different OS).

Looking at the test code, it looks like it runs it's own rendezvous server...

https://github.com/ipfs-shipyard/peer-star-app/blob/master/.aegir.js#L3
https://github.com/ipfs-shipyard/peer-star-app/blob/master/test/utils/create-app.js#L7

**Comment by pgte** [comment]
@jimpick which version of peer-star-app are you testing with?

**Comment by jimpick** [comment]
The master branch on github.

**Comment by pgte** [comment]
Yeah, it's happening sometimes on CI:
![build__602_-_ipfs-shipyard_peer-star-app_-_travis_ci](https://user-images.githubusercontent.com/47910/49278853-d9627d80-f47d-11e8-96d7-9d90b2704397.png)

**Comment by pgte** [comment]
It's random and apparently only occurs when running the tests together.
Since we're using the same rendezvous server process for all the tests, I suspect this happens because we're using the same collaboration name for some tests, which may cause uncaught errors when stopping apps / collaborations.

At least this is my theory..

I think we still need to find the source of the uncaught errors, but I'll try modifying the test collaboration names so that it doesn't conflict.

**Comment by pgte** [comment]
master tests look ok now.
@jimpick do you mind running them locally?

**Comment by pgte** [comment]
Test output is so clean now! :)
![1__bash](https://user-images.githubusercontent.com/47910/49284091-7677e300-f48b-11e8-98e2-aeec7607e622.png)

**Comment by pgte** [comment]
I haven't seen this in the wild. Please reopen this if you find this is not the case.

**Comment by jimpick** [comment]
Still happening...

```
1) collaboration
       closes peer:
     Error: Uncaught Error: stream ended with:0 but wanted:1 (webpack://peerstarapp/node_modules/node-libs-browser/node_modules/events/events.js:59 <- node_modules/aegir/src/config/karma-entry.js:471988)



  2) collaboration
       "after all" hook:
     Error: Uncaught Error: stream ended with:0 but wanted:1 (webpack://peerstarapp/node_modules/node-libs-browser/node_modules/events/events.js:59 <- node_modules/aegir/src/config/karma-entry.js:471988)
```

On OS X (first pass passed, second pass failed):

```
commit e667b53d3cdbf8e2b5f6c21caf3bd988bb5b69f3 (HEAD -> master, upstream/master, origin/master, origin/HEAD)

$  uname -a
Darwin jpmbp2.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
$ node -v
v10.13.0
```

Also on Linux:

```
  1) collaboration
       closes peer:
     Error: Uncaught Error: stream ended with:0 but wanted:1 (webpack://peerstarapp/node_modules/node-libs-browser/node_modules/events/events.js:59 <- node_modules/aegir/src/config/karma-entry.js:465862)
```

```
commit e667b53d3cdbf8e2b5f6c21caf3bd988bb5b69f3 (HEAD -> master, origin/master, origin/HEAD)
$ uname -a
Linux nuc 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ node -v
v10.13.0
```

**Comment by jimpick** [comment]
I was using a js-ipfs build via `npm link ipfs` ... i'm re-running the tests again with the js-ipfs from npm.

**Comment by jimpick** [comment]
I'm going to close this ... i think the problem was with my js-ipfs build.
