### ISSUE TITLE
Reduce the size of vector clocks

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peer-star-app#173]
Right now, the vector clocks are an object that has peer ids as keys.
Since a vector clock only makes sense within a specific collaboration, the probability of id collision for a collaboration with 100 peers is around 4.32 x (10^-74).

The hash collision probability formula is:
N=number of peers
B=number of bits

0.5*(N/(2^(B/2)))^2

If we fix the N to 100, the collision probabilities are:

32 bits: 0.000001164153218
64 bits: 2.710505431213761e-16
128 bits: 1.469367938527859e-35
256 bits: 4.318084277547222e-74

I think we're pretty safe to use 64 bits, which, when base-64 encoded (because JS requires strings), is 12 characters length, which is quite the reduction from the current 46 characters (QmHash.length).

For a 100 peer collaboration, that's a reduction of 3400 bytes __per vector clock__. Since a vector clock is used in every delta, and if a document has endured 1000 changes, that's a maximum reduction of 1000 changes * 100 peers * 3400 = 340 Mbytes in network traffic throughout the life of this document!

Any comments?

**Comment by dirkmc** [comment]
In general I think this idea makes sense, although I have a couple of questions:
1. Are communications compressed somewhere in the transport layer?
2. Is there a more space-efficient encoding than base-64 strings?
3. When you say "JS requires strings" what do you mean exactly?

**Comment by pgte** [comment]
@dirkmc 

1. I don't think they are
2. Good call, I think so: https://github.com/amosyuen/radix64
3. To make unique entries on a native Map, we need strings (otherwise searching for a key would be too complex)

**Comment by dirkmc** [comment]
Actually I think you can use anything for a Map key. According to MDN:
‘The Map object holds key-value pairs and remembers the original insertion order of the keys. Any value (both objects and primitive values) may be used as either a key or a value.’

**Comment by dirkmc** [comment]
Ah yes that's true.

What I was thinking is that internally vector-clock can use whatever type for keys, as long as it can be converted to a string (eg Buffer). When the data is marshalled and sent across the wire it can be converted into some efficient encoding (and compressed etc)

**Comment by dirkmc** [comment]
The maximum value we are trying to use as a key is 32 bytes long, so I considered interpreting the value as a uint32 and using a number for the key instead of a string. However even if you use a number as the key in a Javascript object, it converts it to a string.
```Javascript
> typeof Object.keys({ 42: 1 })[0]
'string'
```

I tried using a Map, but msgpack's encode function produces a larger output for Maps than for a regular Javascript object.
```Javascript
> encode({ 42949: 1 }).toString('hex')
'81a5343239343901'
> encode(new Map([[42949, 1]])).toString('hex')
'c706409192cda7c501'
```

I got optimal results by interpreting the id as a number and then encoding to a string with radix64 and using that as the key in a regular Javascript object:
```Javascript
// Using the number 42949
> encode(new Map([[radix64.encodeInt(42949), 1]])).toString('hex')
'c707409192a339553401'
> encode({42949: 1}).toString('hex')
'81a5343239343901'
> encode({[radix64.encodeInt(42949)]: 1}).toString('hex')
'81a339553401'

// Using the number 4294967296 (2^32)
> encode(new Map([[radix64.encodeInt(4294967296), 1]])).toString('hex')
'c70a409192a6332d2d2d2d2d01'
> encode({4294967296: 1}).toString('hex')
'81aa3432393439363732393601'
> encode({[radix64.encodeInt(4294967296)]: 1}).toString('hex')
'81a6332d2d2d2d2d01'
```
