### ISSUE TITLE
membership sim doesn't seam to be working

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peer-star-app#174]
Followed the instructions [here](https://github.com/ipfs-shipyard/peer-star-app/blob/master/docs/MEMBERSHIP-SIM.MD), tried it in Safari and Chrome against the latest and it looks like it's not working.

Probably the fault of recent changes..

**Comment by pgte** [comment]
@dirkmc could you take a look?

**Comment by dirkmc** [comment]
Fixed by https://github.com/ipfs-shipyard/peer-star-app/pull/175
