### ISSUE TITLE
better persistence indicators

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peer-star-app#189]
In order to determine if it's safe or not to close an app, the app needs to be able to determine if:

- the number of pinners listening to the collaboration
- if / when the latest state has been pinned by any pinner

For this, I propose the following additions to the `collaboration.persistence` API:

```js
collaboration.persistence.pinnerPeers() // => set of PeerId

collaboration.persistence.isCurrentStatePersistedOnPinner() // => boolean

collaboration.persistence.currentStatePersistedOnPinners() // => set of PeerId
```

**Comment by jimpick** [comment]
It's probably not something to worry about yet ... but I've been thinking about whether or not we need the concept of "trusted pinners" ... because anybody can hook up a pinner to a collaboration, there's not guarantee that they'll keep them online for when they are needed later. It might be nice if the application could tell if the data was pinned into a pinner that was part of the infrastructure for the app, or even a pinner that is run by one of your friends...

**Comment by pgte** [comment]
@jimpick good idea. The set of trusted pinners could easily be a configuration option..

**Comment by pgte** [comment]
I'm going to start implementation of this. If you have anything to say, please say it now. :)

**Comment by parkan** [comment]
> 
> 
> It's probably not something to worry about yet ... but I've been thinking about whether or not we need the concept of "trusted pinners" ... because anybody can hook up a pinner to a collaboration, there's not guarantee that they'll keep them online for when they are needed later. It might be nice if the application could tell if the data was pinned into a pinner that was part of the infrastructure for the app, or even a pinner that is run by one of your friends...

this makes a lot of sense from a usability perspective, but also puts us on a path of bandaids leading back to centralization

ways I can think of solving this in a more decentralized-first manner:
- pinners present their identity via HD certificate (for example official PL PeerPad pinners have certificates derived from the https://peerpad.net SSL cert)
- pinner is paid in filecoin, status shows $FC balance for the collab
- pinner must be explicitly invited by participant holding keys

options 1 and 2 are not entirely practical today, but I wonder if pinner access can be restricted in some simpler way for now

**Comment by pgte** [comment]
Provided by #192 

Discussion regarding pinners can be continued in #193.
