### ISSUE TITLE
The `state changed` event is fired multiple times when syncing with a replica

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/peer-star-app#19]
Considering the [todo-app](https://github.com/ipfs-shipyard/workshop-todo-app), when a new peer joins a todo collaboration, there's a lot of `state changed` events fired until it's fully synched with the other replicas.

Without any throttling/debouncing, this causes a lot of changes on the UI, kind of replaying the whole mutations history. Is this desired behavior?

**Comment by satazor** [comment]
@pgte Yes, but we need to be careful in how we do this. Some issues:

- If the event is debounced or throttled, the app "view" of the state might not be in sync during the "wait" amount. This means that if a user does a mutation in these out-of-sync windows using an outdated "view" might cause issues. For instance, consider a "remove" operation that finds a index and calls `removeAt(index)`.
- Ideally, our own mutations should immediately trigger a "state change" without any delays. Not doing so, will make the app look "sluggish".

Take a look at I'm dealing with this issue for now: https://github.com/ipfs-shipyard/workshop-todo-app/blob/54cc8a8000c91125de54dd674f8b5a92c6c5671b/src/todos-store.js#L25

Would it be possible for `state changed` to be fired with an argument telling that the mutations were from our own replica. I don't know if this is possible due to the internals.

**Comment by pgte** [comment]
@satazor it happens that I have a good use for the `state change` event, which is to synchronise local changes and remote changes in exclusivity (I need to reflect the remote changes immediately so that I know all the state when emitting the local changes).

What about I provide you with something like a `debounced state change` event?

**Comment by pgte** [comment]
#23 is a PR for this.
If provides 2 new features:

`stage changed` event has an argument saying whether the change is local or not:

```js
collab.on('state changed', (fromSelf) => {})
```

A new `debounced state changed` that occurs after `options.debounceChangeEventsMS` milliseconds from the last `state changed` event:

```js
collab.on('debounced state changed', () => {})
```

@satazor Do you think this suits your needs?

**Comment by satazor** [comment]
Yep #23 is good. That solves my use-case. For reference, I'm listening for the `state changed` event and update the `todos` variable with the `collaboration.shared.value()`, without any throttling. This ensures that the model is always in sync with the CRDT. The view being out-of-sync is non-issue in my case because operations on the modal are always performed by `id` and not indexes.

Regarding the original issue: perhaps we could attempt to solve the burst of "state changed" events more transparently? I'm thinking if we could buffer the updates coming from a replica and throttle them. 

Could we schedule a call tomorrow to brainstorm ideas?

**Comment by pgte** [comment]
@satazor you're right: throttling and buffering updates coming from a replica is probably the best way to solve this.

**Comment by pgte** [comment]
Yes, remote changes are batched up, they should not flicker any more.
Please reopen if you find it's not the case.
