### ISSUE TITLE
Error when a connection to a peer is closed abruptly 

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/peer-star-app#20]
To replicate this simply start two collaborations on different browsers and refresh one of them.

![capturar](https://user-images.githubusercontent.com/1017236/43056688-845ddf0e-8e35-11e8-8e64-d4a016a7d30b.PNG)

Printing a error in the console seems a bit too much. We already have `peer disconnected` events (and friends) to handle these situations.

**Comment by pgte** [comment]
Version 0.4.4 now masks these errors.
