### ISSUE TITLE
RFC: make embeddings automatic and easy?

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peer-star-app#24]
Embedding a CRDT into another CRDT requires you to explicitly create a sub-CRDT and somehow referencing it in the base CRDT.

I'm thinking of an automated way to detect existing and new CRDTs and creating the sub-CRDTs automatically.

Example:

```js
const arrayCollab = await app.collaborate('some name', 'rga')
const reg = collaboration.embed('lwwreg')
reg.write('value')
arrayCollab.shared.push(reg)

 // collab.shared.value() is recursive:
const arr = collaboration.shared.value() // => ['value']
```

Another option is to, instead of this, invest in creating a delta-based JSON-CRDT, which provides easier and more predictable semantics for handling conflicts.

@satazor any comments / ideas on this?

**Comment by satazor** [comment]
I was about to create the same issue aahaha. We definitively need this!

Let's put it this way: does it make sense for developers using `delta-crdts` have the ability to combine multiple CRDT types in a nested way? I'm inclined in saying yes. Having that said, I think we should look into having JSON like CRDT where we could express the CRDT type for each field.

**Comment by pgte** [comment]
`delta-crdts` package already provide that.
