### ISSUE TITLE
Diffs in state change events

### ISSUE THREAD

**Issue by parkan** [ipfs-shipyard/peer-star-app#38]
(this is an experimental feature request to support work at DWeb summit)

We are using a peer-star-app collaboration based on g-set for a simple weakly ordered [event log](https://github.com/parkan/biome) type app backing an [installation](https://decentralizedweb.net/distributed-gardens/) at the DWeb summit. The API for this use case requires getting the diff (new events added) for each update, in addition to full state update.

**Comment by pgte** [comment]
It's still an undocumented feature, but now you can listen to `change` events on the `collaboration.shared` object. Using a g-set as an example

```js
collaboration.shared.on('change', (change) => {
  console.log(change) // { add: 'a' }
}
collaboration.shared.add('a')
```

A `change` event is emitted after the new state is applied and before the `state changed` event is emitted. There can be many `change` events (as a result of a joint delta) before a `state changed` occurs.

@parkan Please reopen this one if this doesn't work.

**Comment by pgte** [comment]
Forgot to tell you: this works in peer-star-app version 0.5.3.

**Comment by parkan** [comment]
It works! Huzzah
