### ISSUE TITLE
provide replication events

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peer-star-app#50]
The user should be informed of when a remote replica is up to date with your modifications, so that he may be informed about the persistence of its changes.

- [ ] be informed with event of when replica has acknowledged it has our data
- [ ] be informed with event of when replica has data we don't have
- [ ] be informed with event of when a pinner has acknowledged it has our data

**Comment by pgte** [comment]
@andreforsousa @parkan ^^ this may interest you (if / once applied to Peer-Pad).

**Comment by parkan** [comment]
just for clarification, replica = normal peer (not a pinner)?

**Comment by pgte** [comment]
@parkan that's correct. I make the distinction because, for private collaborations, the pinner doesn't understand the state.

**Comment by pgte** [comment]
@parkan and also because the user may want to distinguish between replicating to a pinner from replicating to a "normal" replica. Both signals transmit, in theory, different persistence guarantees.

**Comment by pgte** [comment]
Done in 3228f466e84d99179227d97931e3d9832e15a1ac
