### ISSUE TITLE
Stop the app when there are no collaborations left

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/peer-star-app#76]
As some of you know, I'm developing the discussify app as a chrome extension. Because the background script of the extension is persistent (always running), I don't want to keep unnecessary connections.
More specifically, if there's no active discussion collaborations in any of the tabs after a long period of time, there's no need to have IPFS running and having it keeping connections to other peers.

Ideally, I would want to start the peer-star-app whenever a discussion is started and stop it whenever there are no more active collaborations.

I can do this myself by doing a wrapper that starts and stops collaborations and keeping a counter. Whenever that counter reaches 0, I can stop the app after some predefined amount of time. Though, perhaps we can make this more straightforward by having `start collaboration` and `stop collaboration` events emitted on the app where the first argument could be the number of active collaborations within the app. This way, I could listen to them and call `.stop` after a small amount of time.

```js
const app = peerStarApp('Discussify');

let stopTimeout;

app.on('start collaboration', (collaboration, collaborationsCount) => {
  clearTimeout(stopTimeout);
});

app.on('stop collaboration', (collaboration, collaborationsCount) => {
  if (collaborationsCount === 0) {  
      clearTimeout(stopTimeout);
      stopTimeout = setTimeout(() => app.stop(), 30000);
  }
});
```

Another solution would be to have this functionality built-in, via an option such as `autoStopTimeout`, where it's default value would mean to keep the app running even if there are no active collaborations. Though, it seems kind of ackward.

Thoughts?

**Comment by pgte** [comment]
This one is tricky: when stopping, you also stop IPFS. If you want to restart, mind you that there may be problems restarting IPFS.

Anyway, I think you have all the necessary events you need. I recommend something like the following logic:

```js
let stopped = false
let collabCount = 0

function startCollaboration (...) {
  if (stopped) {
    stopped = false  // make sure we don't start it twice in a row
    await app.start()
  }
  collabCount++
  const collaboration = await app.collaborate(...)
  collaboration.once('stopped', () => {
    collabCount--
    maybeStopApp()
  })
  // also handle collaboration errors here?
}

function maybeStopApp () {
  if (collabCount === 0 && !stopped) { // make sure we don't stop it twice in a row
    stopped = true
    await app.stop()
  }
}
```

Again, please tell me if this works for you (I don't think we have tests for start/stop/start)...

**Comment by satazor** [comment]
> This one is tricky: when stopping, you also stop IPFS. If you want to restart, mind you that there may be problems restarting IPFS.

Hmm, I see. What problems did you find when restarting?

------------------

I totally missed those events, but they require to do a wrapper o peer-star-app as you exemplified. I will resume this later on when we dedicate some time in improving performance of discussify.

**Comment by pgte** [comment]
@satazor it was some time ago so I'm not sure it still is a problem.

**Comment by pgte** [comment]
@satazor mind you that if you plan to stop and start, you should also check if the app is not stopping. If it's stopping, you should wait for it to stop before trying to start again.
Closing this one for now, please reopen if you find problems with this approach.
