### ISSUE TITLE
duplicate maddrs in the membership CRDT

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/peer-star-app#97]
Here's an example of some corruption sneaking into the membership CRDT:

(simulated here)

https://gist.github.com/jimpick/57b0f1898d223b5e41620f0f0cf94a51

The problem is that arrays are being stored as leaves in the ORMap, but JavaScript doesn't consider them to be equal, so the Set after joining will contain 2 arrays.

I'm not sure if the correct solution is to not store arrays (eg. serialize to a string), or perhaps modify the CRDT join to do a deep equals...

**Comment by pgte** [comment]
@jimpick I think this behaviour is expected. An Multi-value register is a register that exposes concurrent values.

In this case, it looks like the concurrent values are exposed correctly. Then it's up to the application to resolve them using whatever merge function they prefer.

In the case of peer-star-app, the value join function is [this one](https://github.com/ipfs-shipyard/peer-star-app/blob/master/src/collaboration/membership.js#L279-L282).

What I think is missing here is deduplicating addresses in this `joinAddresses` function.

@jimpick would you agree?

**Comment by jimpick** [comment]
I was a bit surprised by the behaviour. I'll look at what joinAddresses does...

Another approach might be to use something like immutable.js when deserializing - I believe that would make the objects pass the equality check. But it's another dependency.

**Comment by pgte** [comment]
Deduplication of addresses landed in v0.9.2
